config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    like = current_user.likes.create(post_id: params[:post_id])
    like.save
    render 'create.js.erb'
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    render 'destroy.js.erb'
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="likes">いいね：
<% if user_signed_in? && post.liked_by?(current_user)%>
  <%=link_to post_likes_path(post.id),  method: :delete, class: "post_likes" , remote: true do %>
  <i class="fa-solid fa-heart", style="color:pink;"></i>
  <% end %>
<% else %>
  <%=link_to post_likes_path(post.id), method: :post, class: "post_likes" , remote: true do %>
  <i class="fa-regular fa-heart", style="color:black;"></i>
  <% end %>
<% end %>
<p class ="likes_count"><%= post.likes.count %></p>
</div>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @post.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @post.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"