config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  with_options presence: true do
    validates :nickname
    validates :profile, length: { maximum: 150 }
  end
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'is invalid. Include both letters and numbers' }, on: :create

  def followed_by?(user)
    follower = passive_relationships.find_by(following_id: user.id)
    follower.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :move_to_index]
  before_action :move_to_index, only: :edit
  def show
    @posts = @user.posts
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index
    return if user_signed_in? && current_user.id == @user.id

    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="user-edit">
  <div class="user-edit_main">
  
    <div class="user-edit__form">
      <%= form_with(model: @user, local: true) do |f| %>
        <%= render "shared/error_messages", model: f.object %>

        <div class="user_edit_field">
          <p class="edit_name">メールアドレス</p>
          <%= f.email_field :email, class: "edit_email", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="user_edit_field">
          <p class="edit_name">ニックネーム</p>
          <%= f.text_field :nickname, class: "edit_nickname", maxlength: "20" %>
        </div>

        <div class="user_edit_field">
          <p class="edit_name">プロフィール(150字まで)</p>
          <%= f.text_area :profile, class: "edit_form_text" ,maxlength:"150" %>
        </div>

        <div class="user_edit_actions">
          <%= f.submit "編集完了", class: :edit_form_btn %>
        </div>
      <% end %>
    </div>
  </div>
    <div class="return-page">
    <%= link_to "戻る", user_path(@user.id), class: "return_page" %>
    </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="user_page">
  <div class="user_page_main">
    <div  class="user_page_head">
      <p class="user_name">
        <%= @user.nickname %>
      </p>
      <div class="user_profile_contets">
        <ul class="user_profile">
            <li>フォロワー数：<%= @user.followers.count %></li>
            <li>投稿数：<%= @user.posts.count %></li>
            <li>プロフィール：<%= @user.profile %></li>
        </ul>
        <%#編集ボタンの設置%>
        <% if user_signed_in? && current_user.id == @user.id %>
          <div class="user_edit_button"> 
          <%= link_to "編集する",edit_user_path(@user.id) %>
          </div>
        <% end %>
        <%#編集ボタンの設置%>
        <%#フォローボタンの設置%>
          <% if user_signed_in? && current_user != @user %>
          <div class="user_follow">
            <% if @user.followed_by?(current_user) %>
              <%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
            <% end %>
          </div>
          <% end %>  
        <%#//フォローボタンの設置%>
      </div>
    </div>
    <%#ユーザー投稿一覧%>
    <div class="user_page_row">
      <div class="user_post_list">
        <% @posts.each do |post| %>
        <div class="user_post__lists">
          <%= link_to post_path(post.id) do %>
          <p class="user_post_img">
          <%= image_tag post.images[0], class: "user-image" %>
          </p>
          <p class="user_post_title">タイトル：
          <%= link_to post.title, post_path(post.id) %>
          </p>
          <p class="user_post_category">カテゴリ：
          <%= post.category.name %>
          </p>
          <p class="user_post_title">予　算　：
          <%= post.budget %>円
          </p>
          <% end %>
          <p class="user_post_created_at">投稿日：
          <%= post.created_at.strftime("%Y-%m-%d") %>
          </p>
        </div>
        <% end %>
      </div>
    </div>
    <%#ユーザー投稿一覧%>
    <%= link_to "Topへ戻る", root_path, class: "return_top" %>
  </div>
</div>
<%= render "shared/footer" %>