config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="footer-logo">©︎ TRIP LOG</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='page-header wrapper'>
  <div class="heading-left">
    <%= link_to 'TRIP LOG', root_path, class:"title-logo" %>
    <h2 class="sub-title-logo">〜旅を楽しむ〜</h2>
  </div>

  <div class="current-user">
    <% if user_signed_in? %>
      ようこそ、<%= "#{current_user.nickname}" %>さん
    <% end %>
  </div>

  <nav>
    <ul class='main-nav'>
    <% if user_signed_in? %>
    <li><%= link_to 'SEARCH', search_posts_path %></li>
    <li><%= link_to 'MYPAGE', "/users/#{current_user.id}" %></li>
    <li><%= link_to 'NEWPOST', new_post_path %>
    <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to 'SEARCH', search_posts_path %></li>
    <li><%= link_to 'LOGIN', new_user_session_path %></li>
    <li><%= link_to 'CREATE NEW ACCOUNT', new_user_registration_path %></li>
    <% end %>
    </ul>
  </nav>
</header>