config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :opening_hour
  belongs_to :area
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  has_many :post_tag_relations
  has_many :tags, through: :post_tag_relations, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/post_form.rb
class PostForm
  include ActiveModel::Model

  attr_accessor(
    :title, :text, :address, :images,
    :category_id, :budget, :opening_hour_id,
    :id, :created_at, :updated_at,
    :user_id, :tag_name, :area_id
  )

  with_options presence: true do
    validates :title, length: { maximum: 50 }
    validates :text, length: { maximum: 2000 }
    validates :address, length: { maximum: 200 }
    validates :images
    validates :budget, numericality: { only_integer: true, message: 'is invalid. Input half-width characters' }
    validates :category_id, :opening_hour_id, :area_id, presence: { message: "can't be blank" }
    validates :user_id, presence: { message: 'must exist' }
  end
  validates :category_id, :opening_hour_id, :area_id, numericality: { only_integer: true }, allow_blank: true
  validates :images, length: { minimum: 1, maximum: 5, message: 'must be one or no more than five' }
  validates :budget,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999, message: 'is out of setting range' }, allow_blank: true
  validates :tag_name, length: { maximum: 20 }

  def save
    post = Post.create(title: title, text: text, address: address, images: images, category_id: category_id, budget: budget,
                       opening_hour_id: opening_hour_id, user_id: user_id, area_id: area_id)
    return unless tag_name.present?

    tag = Tag.where(tag_name: tag_name).first_or_initialize
    tag.save
    PostTagRelation.create(post_id: post.id, tag_id: tag.id)
  end

  def update(params, post)
    post.post_tag_relations.destroy_all
    tag_name = params.delete(:tag_name)
    tag = Tag.where(tag_name: tag_name).first_or_initialize if tag_name.present?
    tag.save if tag_name.present?
    post.update(params)
    PostTagRelation.create(post_id: post.id, tag_id: tag.id) if tag_name.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_post, only: [:show, :destroy, :edit, :update]
  before_action :set_post_form, only: [:create, :update]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post_form = PostForm.new
  end

  def create
    if @post_form.valid?
      @post_form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    post_attributes = @post.attributes
    @post_form = PostForm.new(post_attributes)
    @post_form.tag_name = @post.tags.first&.tag_name
  end

  def update
    @post_form.images ||= @post.images.blobs
    if @post_form.valid?
      @post_form.update(post_form_params, @post)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    if params[:q]&.dig(:title)
      squished_keywords = params[:q][:title].squish
      params[:q][:title_cont_any] = squished_keywords.split(' ')
    end
    @q = Post.ransack(params[:q])
    @posts = @q.result.order(created_at: :desc)
  end

  private

  def post_form_params
    params.require(:post_form).permit(:title, :text, :address, :category_id, :budget, :opening_hour_id, :tag_name, :area_id,
                                      { images: [] }).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_form
    @post_form = PostForm.new(post_form_params)
  end

  def move_to_index
    return if current_user.id == @post.user_id

    redirect_to root_path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts_form">
   <%= form_with model: @post_form, url: url, method: method, id: 'new_post', local: true do |f| %>
      <%= render "shared/error_messages", model: f.object, class: "posts-form-error" %>
      <!--div class="post__form"-->    
         <div class ="post_field">
         <p class ="select-name">タイトル（50字以内）</p>
         <%= f.text_field :title, maxlength: "50", class: "new__title" %>
         </div>

         <div class="post_text_field">
         <p class="select-name">詳細（2000字以内）</p>
         <%= f.text_area :text, maxlength: "2000", class: "new__text" %>
         </div>
         
         <div class="post_field">
         <p class="select-name">住所（200字以内）</p>
         <%= f.text_field :address, class: "new__address" %>
         </div>

         <div class="post_select">
         <p class="select-name">エリア</p>
            <%= f.collection_select(:area_id, Area.all, :id, :name, {include_blank: '--- 全てのエリア ---'}, class:"select-box") %>
            <p class="select-name">カテゴリー</p>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: '-----'}, class:"select-box") %>
            <p class="select-name">予算</p>
            <%= f.text_field :budget, class: "new__budget", placeholder: "¥0〜9,999,999" %>
            <p class="select-name">営業時間</p>
            <%= f.collection_select(:opening_hour_id, OpeningHour.all, :id, :name, {include_blank: '-----'}, class:"select-box") %>
         </div>

         <div class="post_tag_field">
            <p class="select-name">タグ</p>
            <%= f.text_field :tag_name, class:"post__tag" %>
         </div>

         <div class="post_image_field">
         <div id='previews'></div>
            <p class="select-name">画像を添付してください（最大5
            枚まで）</p>
            <div class="click-upload">
            <%= f.file_field :images, name: 'post_form[images][]', data: {index: 0} %>
            </div>
         </div>   
         <br>

         <div class="post_action">
         <%= f.submit "投稿する", class: "post-submit-btn" %>
         </div>
      <!--/div-->
      <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "shared/header" %>
<div class="post_new">
  <div class="post_new_main">
    <%= render partial: 'form', locals: {url: post_path(@post.id), method: :patch} %>
    <div class="post_new_btn">
    <%= link_to '戻る', post_path(@post.id), class: "back_btn" %>
  </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>
  <div class="top_main">
  <div class="header_contents">
  <!--セカンドヘッダー-->
    <div class ="subtitle">
      <h1 class="subtitle_main">Find your special trip</h1>
      <p class="subtitle_second">あなたにピッタリの旅を見つけませんか？</p>
    </div>
    <!--検索バー-->
    <div class="search-bar">
      <%= search_form_for Post.ransack(params[:q]), url: search_posts_path, html: { class: "top-search-form"} do |f| %>
        <%= f.text_field :title, placeholder: 'タイトルから探す', class: 'top-input-box' %>
        <br>
        <%= f.label :submit, class: "top-search-button" do %>
          <input type="submit" value="検索" class="top-search-send">
          <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
        <% end %>
      <% end %>
    </div>
    <!--検索バー-->
  </div>
  <!--セカンドヘッダー-->
  <div class="posts_main">
    <div class="posts_lists">
      <% @posts.each do |post| %>
      <div class="post_list">
        <%= link_to post_path(post.id) do %>
          <div class="post_img">
            <%= image_tag post.images[0], class: 'post-image' %>
          </div>
          <div class="post_list_text">
            <p class="post_title">
              タイトル：<%= post.title %>
            </p>
            <p class="post_category">
              カテゴリ：<%= post.category.name %>
            </p>
        <% end %>
          <p class="post_budget">
            予　算　：<%= post.budget %>円
          </p>
          <p class="post_created_at">
            投稿日：<%= post.created_at.strftime("%Y-%m-%d") %>
          </p>
          </div>
      </div>
      <% end %>
    </div>
  </div>
  <!--投稿一覧-->
  </div>
  <%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class="post_new">
  <div class="post_new_main">
    <%= render partial: 'form', locals: {url: posts_path, method: :post} %>
    <div class="post_new_btn">
    <%= link_to 'Topへ戻る', root_path, class: "back_btn" %>
  </div>
  </div>
</div>

<%= render "shared/footer" %>
    

app/views/posts/search.html.erb
<%= render "shared/header" %>
<div class="post-search-contents" id ="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_posts_path, html: {id: "detailed-search-form"}, class: "search-form" do |f| %>
  <h2 class="search-form-title">Find your special trip</h2>
    <div class="search-field">
      <%= f.label :title, 'タイトル', class: "search-name" %>：
      <%= f.text_field :title, class: "search-title", placeholder: 'タイトルから検索', value: params[:q]&.dig(:title) %>
    </div>
    <div class="search-field">
      <%= f.label :tags_tag_name_cont, 'タグ', class: "search-name" %>　　：
      <%= f.text_field :tags_tag_name_cont, class: "search-title", placeholder: 'タグから検索' %>
    </div>
    <div class="search-field">
      <%= f.label :category_id_in, 'カテゴリ', class: "search-name" %>：
      <%= f.collection_check_boxes(:category_id_in, Category.all, :id, :name) %>
    </div>
    <div class="search-field">
      <%= f.label :budget_gteq, '予算', class: "search-name" %>　　：
      <%= f.number_field :budget_gteq %> 円以上、<%= f.number_field :budget_lteq %> 円以下
    </div>
    <div class="search-field">
      <%= f.label :opening_hour_id_in, '営業時間', class: "search-name" %>：
      <%= f.collection_check_boxes(:opening_hour_id_in, OpeningHour.all, :id, :name) %>
    </div>
    <div class="search-field">
      <%= f.label :area_id_in, 'エリア', class: "search-name" %>　：
      <%= f.collection_check_boxes(:area_id_in, Area.all, :id, :name) %>
    </div>
    <div class="search-send-button">
      <%= f.submit '検索', class: "search-send"%>
    </div>
  <% end %>
</div>
  <div class="search_main">
    <div class="search-lists">
      <% @posts.each do |post| %>
      <div class="search-result-list">
        <%= link_to post_path(post.id) do %>
          <div class="posted__img">
            <%= image_tag post.images[0], class: 'posted-image' %>
          </div>
          <div class="posted_list_text">
            <p class="posted_title">
              タイトル：<%= post.title %>
            </p>
            <p class="posted_category">
              カテゴリ：<%= post.category.name %>
            </p>
        <% end %>
            <p class="posted_budget">
              予　算　：<%= post.budget %>円
            </p>
            <p class="posted_created_at">
              投稿日：<%= post.created_at.strftime("%Y-%m-%d") %>
            </p>
          </div>
      </div>
      <% end %>
    </div>
    <h3 class="back-top"><%= link_to 'Topへ戻る', root_path %></h3>
  </div>

<%= render "shared/footer"%>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class="post_show">
  <div class="post_shows">
    <div class="post_shows_main">    
      <div class="other-images">
        <%= image_tag @post.images[0], class: "post-show-img" %>
        <% @post.images[1..-1].each do |image| %>
            <%= image_tag image, class: "post-show-img" %>
        <% end %>
      </div>
      <div class="post_text_main">      
        <div class="post_shows_title">
          <%= @post.title %>
        </div>
        <div id="like-btn<%= @post.id %>">
          <%= render partial: "likes/like", locals: {post: @post} %>
        </div>
        <div class="post_show_foot_field">
          投稿者：<%= link_to "#{@post.user.nickname}", user_path(@post.user) %>
        </div>
        <ul class="post_text__contents">
          <li class="post_shows_field">
            カテゴリー：<%= @post.category.name %>
          </li>

          <li class="post_shows_field">
            予算：<%= @post.budget %> 円
          </li>

          <li class="post_shows_field">
            営業時間：<%= @post.opening_hour.name %>
          </li>

          <li class="post_shows_field">
            エリア：<%= @post.area.name %>
          </li>

          <li class="post_shows_field">
            住所：<%= @post.address %>
          </li>
        </ul>
          <div class="post_shows_text_field">
            <p class="post_show_text">
            <%= @post.text %>
            </p>
          </div>
          <ul class="post_show_foot">
            <li class="post_show_foot_field">
            投稿日：<%= @post.created_at.strftime("%Y-%m-%d") %>
            </li>
            <li class="post_show_foot_field">
              ＃<%= @post.tags.first&.tag_name %>
            </li>
          </ul>
      </div>
    </div>
    <div class="post_manage">
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class= "post_manage_btn">
        <%= link_to "編集", edit_post_path(@post.id), class: "manage-btn" %>
        </div>
        <div class="post_manage_btn">
        <%= link_to "削除", post_path(@post.id), method: :delete, class: "manage-btn" %>
        </div>
      <% end %>
    </div>
    <div class="comment-contents">
      <div class="comment-form">
        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>
              <%= f.text_area :text, class: "comment-text" %>
              <%= f.submit "コメントする", class: "comment-submit" %>
          <% end %>
        <% end %>
      </div>
      <div class="comment-result-form">
        <h4 class="comments-list">【コメント一覧】</h4>
        <div class="comments-result">
          <div id="comments">
            <% @post.comments.each do |comment| %>
              <div class="comment">
                <p class="user-info"><%= link_to "#{comment.user.nickname}", user_path(comment.user) %> : </p>
                <p><%= comment.text%></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="post_show_btn">
    <%= link_to 'Topへ戻る', root_path, class: "back_btn" %>
  </div>
</div>
<%= render "shared/footer" %>